# Generated by Django 5.1.3 on 2025-06-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cartorder_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
