# Generated by Django 5.1.3 on 2025-05-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_flavor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavor',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='flavors',
            field=models.ManyToManyField(blank=True, to='core.flavor'),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
