# Generated by Django 5.1.3 on 2025-06-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cartorderitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
