# Generated by Django 5.1.3 on 2025-06-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_address_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitem',
            name='invoice_number',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
