# Generated by Django 5.1.3 on 2025-06-15 12:53

import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_cartorderitem_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='invoice_number',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True),
        ),
    ]
