# Generated by Django 5.1.3 on 2025-06-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_cartorder_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('FLUTTER', 'Flutterwave')], default='COD', max_length=20),
        ),
    ]
