# Generated by Django 5.1.3 on 2025-06-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cartorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('FLUTTER', 'Flutterwave')], default='COD', max_length=20),
        ),
    ]
