# Generated by Django 5.1.3 on 2025-07-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_coupon_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='shipping_price',
            new_name='shipping_cost',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='pending', max_length=10),
        ),
    ]
