# Generated by Django 5.1.3 on 2025-07-25 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_shipping_price_cartorder_shipping_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='coupons',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='coupons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coupon'),
        ),
    ]
