# Generated by Django 5.1.3 on 2025-07-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_product_buying_price_alter_cartorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
